### ISSUE TITLE
Why skipping digits!

### ISSUE THREAD

**Issue by BaseMax** [dalirnet/persian-to-slug#11]
### Input
```
برنج قهوه ای ۵ کیلویی
```

### Output
```
brng-ghhoh-kiloii
```

### Expected output
```
...-5-kiloii
```

**Comment by dalirnet** [comment]
Oops, I really don't know !
Before using, replace the digits with your own words, or fork it and remove [this](https://github.com/dalirnet/persian-to-slug/blob/master/index.js#L22) line.

**Comment by BaseMax** [comment]
I fixed it, Now you can close this one.
